version: '3.7'
services:
  # PostgreSQL database
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flight-info
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
